# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11a38aee5c7a961dbb1edefd431d432f99cb91b053091f9b36b35d9bbbd27bb48027b0adf16120bf2d789bbb49420055175b3ea4d70ce082704804882dc9750d

test:
  secret_key_base: dc1fd62ca7502f2b31316c6365494cfa109fdff8a012f2fdbc9e503bd020e94a559a9d53597e7d0cc4eff7fd9a480eea8d381de99a9c82948ee723af45ede5b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
